apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kibana.fullname" . }}-config
data:
  kibana.yml: |
    # Kibana Configuration File
    server.name: kibana
    server.host: "0.0.0.0"
    server.basePath: "/kibana"
    elasticsearch.url: http://data-service:9200
    elasticsearch.username: elastic
    elasticsearch.password: changeme
    # Disable paid X-Pack services, enable freebies
    xpack.graph.enabled: false
    xpack.ml.enabled: false
    xpack.monitoring.enabled: true
    xpack.reporting.enabled: false
    xpack.security.enabled: false
    xpack.monitoring.ui.container.elasticsearch.enabled: true
