# EDCOP Elasticsearch Chart values
images:
  # Base image (es): docker.elastic.co/elasticsearch/elasticsearch:6.2.4
  elasticsearch: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
  curator: bobrik/curator
networks:
  # Overlay is the name of the default cni network
  overlay: calico
volumes:
  # Persistent data location on the host to store Elasticsearch's data
  data: /EDCOP/bulk/esdata
nodeSelector:
  client: worker
  master: master
elasticsearchConfig:
  # runAsUser refers to the UID of the user who owns the persistent data location specified above
  runAsUser: 2000
  # Nodes refers to the number of worker nodes you have
  workerNodes: 3
  env:
    clustername: edcop
    javaopts: -Xms16g -Xmx16g
  # Requests are set to accommodate limited resource VMs
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 4 
    memory: 32Gi
curatorConfig:
  # Input how often the curator should run in cronjob format
  cronjob_schedule: 1 0 * * *
  # Input how many failed/successful pods should be kept after completion (0 for none)
  failedPodsLimit: 1
  successfulJobsLimit: 1     
  actions:
    close:
      # (True or False) Set to False to enable this feature.
      disable_action: False
      # Closes indices older than the specified units
      unit: days
      unit_count: 7
    delete_indices:
      # (True or False) Set to False to enable this feature.
      disable_action: False
      # Deletes indices older than the specified units
      unit: days
      unit_count: 14 
    
